version: '3.8'

services:
  fireredasr-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5078:5078"
    volumes:
      - ./logs:/app/logs
      - ./static/tmp:/app/static/tmp
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5078/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s